# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c84df94a77ea75203591b54cf29f491579b91865d2c40c8a9abc952cfe4b06dcf49d6d76ac91fa2cf8576990fdb68b3d09c7dd8ac3e4632f046924aad8f64ff2

test:
  secret_key_base: 414b133190c8efcc14598b877c41565ccd9f1b2f93d5335e5eba004aa78be422c298aeefc7528d10fc763e2d69ac520d6b1f636ae416183582ebcd2209be2334

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
